services:
  paperless-sync:
    build: .
    container_name: paperless-sync
    ports:
     - 8081:8081
    env_file:
      - .env
    volumes:
      - paperless-sync:/app/data
    restart: "no"

volumes:
  paperless-sync: