[project]
name = "paperless-sync-project"
version = "0.1.0"
description = "Sync documents from paperless-ngx to openwebui kb for RAG context. Original author https://www.reddit.com/user/carlinhush/"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx[http2]>=0.28.1",
    "python-dotenv>=1.1.1",
    "python-slugify>=8.0.4",
    "pyyaml>=6.0.3",
    "tenacity>=9.1.2",
    "tqdm>=4.67.1",
    "typer[all]>=0.19.2",
]
